name: Fetch Federal Drug Files
on:
  workflow_dispatch:
  schedule:
  - cron: "30 8 5 * *"

jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      CI_COMMIT_MESSAGE: Monthly Get Current Drug Files
      CI_COMMIT_AUTHOR: ${{ github.event.repository.name }} MirrorJob
    steps:
      - uses: actions/checkout@v3    
      
      - name: Get Federal Drug Files
        run: ./getDrugFiles.sh
        
      - name: Commit Federal Drug Files
        run: |
          if [ -z "$(git diff --name-only)" ];
          then
            echo "No new files to commit"
          else
            echo "Drug files have been updated"
            git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
            git config --global user.email "drugmirror@users.noreply.github.com"
            git commit -a -m "${{ env.CI_COMMIT_MESSAGE }}"
            git push
          fi
